9/sdk
graasp/graasp-plugin-item-login pull request #10
Opened 2022-07-12 09:30 UTC by pyphilia

close #9

2022-07-27 10:50 UTC, dialexo requested changes
Thanks for this PR 🍘 I have one major security concern, and the `test` command should probably be set to jest. Otherwise, a few nitpicks regarding comments and naming 👍

2022-07-27 10:50 UTC, dialexo commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 0",
Should this be jest?

2022-07-27 10:50 UTC, dialexo commented on src/tasks/item-login-with-member-id-task.ts
>  // global
Should we remove this comment now that the imports sort is automated?
```suggestion

```

2022-07-27 10:50 UTC, dialexo commented on src/tasks/item-login-with-member-id-task.ts
> +// local
Should we remove this comment now that the imports sort is automated?
```suggestion

```

2022-07-27 10:50 UTC, dialexo commented on src/util/aux.ts
> +const randomHexOf4 = () => ((Math.random() * (1 << 16)) | 0).toString(16).padStart(4, '0');
This is probably fine for our purposes, though we may want to use e.g. https://www.npmjs.com/package/random-number-csprng instead. We could imagine an attack where a malicious user is aware of the time of the request of another specific user, and thus could deduce the identity of the pseudonymized user based on their activity.
See https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export const GraaspError = ErrorFactory(PLUGIN_NAME);
```suggestion
export const GraaspItemLoginError = ErrorFactory(PLUGIN_NAME);
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class ItemNotFound extends GraaspError {
```suggestion
export class ItemNotFound extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class MemberIdentifierNotFound extends GraaspError {
```suggestion
export class MemberIdentifierNotFound extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class InvalidMember extends GraaspError {
```suggestion
export class InvalidMember extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class MissingItemLoginSchema extends GraaspError {
```suggestion
export class MissingItemLoginSchema extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class MissingItemLoginTag extends GraaspError {
```suggestion
export class MissingItemLoginTag extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class ValidMemberSession extends GraaspError {
```suggestion
export class ValidMemberSession extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class InvalidCredentials extends GraaspError {
```suggestion
export class InvalidCredentials extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class MissingCredentialsForLoginSchema extends GraaspError {
```suggestion
export class MissingCredentialsForLoginSchema extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class UnnecessaryCredentialsForLoginSchema extends GraaspError {
```suggestion
export class UnnecessaryCredentialsForLoginSchema extends GraaspItemLoginError {
```

2022-07-27 10:50 UTC, dialexo commented on src/util/graasp-item-login-error.ts
> +export class MemberCannotAdminItem extends GraaspError {
```suggestion
export class MemberCannotAdminItem extends GraaspItemLoginError {
```

2022-08-02 12:21 UTC, pyphilia commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 0",
Yes but we don't have test yet.

2022-08-02 12:34 UTC, merged